[workspace]
channels = ["conda-forge"]
name = "high-temperature-raman-challenges"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
plotly = ">=6.3.1,<7"
numpy = ">=2.3.3,<3"
scipy = ">=1.16.2,<2"

[pypi-dependencies]
kaleido = ">=1.1.0, <2"
